# This is a basic workflow to help you get started with Actions

name: Print-PR
on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  prJob:    
    name: Print info
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "part 1 ${{ github.event.action }}"
          echo "part 2 ${{ github.event.pull_request.comment }}"
