# This is a basic workflow to help you get started with Actions

name: Print-PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  prJob:    
    name: Print info
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo oneline script example

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "${{ github.event.type }}"
          echo "${{ github.event.comment.body }}"
          echo "--done--"
